### ISSUE TITLE
doesn't start with latest pngcrush

### ISSUE THREAD

**Issue by ikn** [Kilian/Trimage#45] opened 2017-08-20 17:32 UTC
After upgrading pngcrush from 1.8.11 to 1.8.12, Trimage fails to start.  This happens with both 1.0.5 and the current git version (I'm using the packages in [AUR](https://aur.archlinux.org/)).

```
$ trimage 
 pngcrush 1.8.12, uses libpng 1.6.31 and zlib 1.2.11
 Check http://pmt.sf.net/
 for the most recent version.

usage: pngcrush [options except for -e -d] infile.png outfile.png
       pngcrush -e ext [other options] file.png ...
       pngcrush -d dir/ [other options] file.png ...
       pngcrush -ow [other options] file.png [tempfile.png]
       pngcrush -h or -v -v -h (for help or verbose help) 
       pngcrush -n -v file.png ... (to list chunks)
[error] please install pngcrush
```

**Comment by JoZ3** [comment] 2017-08-28 19:04
Same error here :(

**Comment by Kilian** [comment] 2017-08-29 18:25
I think the return code for the pngcrush version check has changed. I emailed author for more information. I'm on Ubuntu 16.04 myself which still has 1.7.85 so haven't encountered this myself.

**Comment by glennrp** [comment] 2017-08-29 21:00
I'm not sure but will investigate.  I'm planning to release 1.8.13 soon with some changes in this area.

**Comment by Kilian** [comment] 2017-08-30 08:32
@ikn @JoZ3 pngcrush 1.8.13 was just released by @glennrp (so fast!) can you see if the issue is now resolved? https://sourceforge.net/projects/pmt/files/pngcrush/

**Comment by JoZ3** [comment] 2017-08-30 12:14
@Kilian yes works for me. And thanks so much @glennrp

**Comment by Kilian** [comment] 2017-08-30 12:34
whoo! :100: :tada:

**Comment by ikn** [comment] 2017-08-30 17:30
Yeah, same here, works fine.

**Comment by Kilian** [comment] 2017-08-31 11:22
nice, closing this!

**Closed by Kilian** 2017-08-31 11:22 UTC
